In [5]:
#import numpy

import numpy as np
print("Hello")
arr=np.array([1,2,3,4])
print(arr)  #in numpy there is no space in an array
print(type(arr))


Hello
[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
#0D array

arr=np.array(52)
print(arr)

52


In [18]:
#1D array
a1=np.array([1045,20.56,330,"Nisha"])
print(a1)
print(type(a1))
print(a1[-1]) #Access negative index ,index start with -1 to end of array

['1045' '20.56' '330' 'Nisha']
<class 'numpy.ndarray'>
Nisha


In [14]:
#2D array

frut_price=np.array([[10,20,30],[60,40,50]])
print(frut_price)
print(type(frut_price))
print(frut_price[1,2]) #array_name[row,coloum]

[[10 20 30]
 [60 40 50]]
<class 'numpy.ndarray'>
50


In [13]:
#Multidimentinal array

arr1=np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,20,30]]])
print(arr1)
print("Display 6 : ",arr1[0,1,2]) #[matrix,row,coloum]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 20 30]]]
Display 6 :  6
int64


In [10]:
#Numpy function

#Slice
    #index :  -8 -7 -6 -5 -4 -3 -2 -1
arr=np.array([10,20,30,40,50,60,70,80])
    #index :  0   1  2  3  4  5  6  7
print(arr)
print(arr[2:6])#syntax : variable_name[start:end:step] .By default step is 1
print("step 2 : ",arr[1:7:2]) #start=1,end=7,step=2
print(arr[-8:-1])
print(arr.dtype)

[10 20 30 40 50 60 70 80]
[30 40 50 60]
step 2 :  [20 40 60]
[10 20 30 40 50 60 70]
int64


In [ ]:
#Shape and size of array 
arr=np.array([[[10,20,30],
               [50,60,70]],
              [[1,2,3],
               [4,5,6]]])
print(arr.shape) #Shape function are used to calculate no.matrix ,no.row and no.colounm in array
print(arr.size) #It will calculate no.of elements present in array

In [29]:
#reshaping array

arr=np.array([1,2,3,4,5,6,7,8,9])
newarray=arr.reshape(3,3)
print(newarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
#Iteracting array elements
arr=np.array([15,89,65,23,45,56,89])
for i in arr:
    print(i*10)

150
890
650
230
450
560
890


In [ ]:
#Joining array

a1=np.array([10,20,30,58,95])
a2=np.array([10,50,60])
a3=np.concatenate([a1,a2])
print(a3)

In [18]:
#split array (np.array_split(array_name,number))

arr=np.array([10,20,30,40,50,60,70])
newarray=np.array_split(arr,2)
print(newarray)

[array([10, 20, 30, 40]), array([50, 60, 70])]


In [22]:
#serching for array - where is a function that are used to check element present in which index.
#If element are not present in an array then it return blank

arr=np.array([1,45,48,26,79,2,3])
x=np.where(arr==79) #where(array_name == element)
print(x)

(array([4]),)


In [28]:
#Sorting an array

arr=np.array([56,89,23,45,86])
print("Sorted array elements: ",np.sort(arr))

#taking elements from user and sort
arr1=[]
n=int(input("Enter size how many elements you are enter:"))
for i in range(0,n):
    ele=int(input("Enter element: "))
    arr1.append(ele)

print(np.sort(arr1))

Sorted array elements:  [23 45 56 86 89]


Enter size how many elements you are enter: 4
Enter element:  789
Enter element:  56
Enter element:  28
Enter element:  498


[ 28  56 498 789]


In [37]:
#Sort array in desending order

arr=np.array([598,78,26,458,10])
arr=np.sort(arr)
print(arr)
#print(np.sort(arr[::-1]))
print(arr[::-1])

[ 10  26  78 458 598]
[598 458  78  26  10]


In [42]:
##Filtering array

arr=np.array([59,26,89,36,92,97])
x=[True,False,True,False,True,True]
newarr=arr[x]
print(newarr)

[59 89 92 97]


In [56]:
#Filtering elements in array

arr=[]
n=int(input("Enter size of array :"))
for i in range(0,n):
    ele=int(input("Enter element: "))
    arr.append(ele)
arr=np.array(arr)  #we need to convert list into array

filter_array=[]
for i in arr:
    if i>40:
          filter_array.append(True)
    else:
          filter_array.append(False)

new_array=arr[filter_array]
print(filter_array)
print(new_array)


Enter size of array : 3
Enter element:  45
Enter element:  78
Enter element:  96


[True, True, True]
[45 78 96]


In [54]:
#converting data type 

arr=[]
n=int(input("Enter size: "))
for i in range(0,n):
    ele=input("Enter element:")
    arr.append(ele)
arr=np.array(arr)
print(arr.astype(int))

'''
arr=np.array([10,20,30])
print(arr)
print(arr.astype(str))
'''

Enter size:  4
Enter element: 55
Enter element: 88
Enter element: 95
Enter element: 56


['55' '88' '95' '56']
[55 88 95 56]
['55' '88' '95' '56']


'\narr=np.array([10,20,30])\nprint(arr)\nprint(arr.astype(str))\n'

In [20]:
#Adding and removing elements 

arr=np.array([10,20,30,40,50])
print(np.append(arr,[82,48])) #append is a method that are used to add element at end of list or array
print(arr)
arr=np.insert(arr,4,5)#insert method used to insert element at specific index
print(arr)
arr=np.insert(arr,2,[7,8,9])
print(arr)
print(np.delete(arr,[2]))
print(arr)

[10 20 30 40 50 82 48]
[10 20 30 40 50]
[10 20 30 40  5 50]
[10 20  7  8  9 30 40  5 50]
[10 20  8  9 30 40  5 50]
[10 20  7  8  9 30 40  5 50]


In [9]:
#aggregate function

arr=np.array([[100,20,30],[455,70,807]])
print(np.max(arr))
print(np.sum(arr)) #it will return sum of all numbers
print(np.min(arr)) #It will return minimum number among array
print(np.max(arr)) #It will return maximum number among array
print(np.cumsum(arr)) #It will return addition of two numbers into third number

807


In [34]:
#Statistics

import statistics as stat

food_prices=[10,20,30,50,40,50,60,70]
print(food_prices)
a=np.array(food_prices)
print("Array : ",a)
print("Mean : ",np.mean(a)) #mean-it will return average of array
print("Median : ",np.median(a)) #it will return medial value ,
#if means 8 value present in array then it will take average of 4&5 index element
print("Mode :",stat.mode(a)) #it will return most frequently present value, numpy can't support mode

[10, 20, 30, 50, 40, 50, 60, 70]
Array :  [10 20 30 50 40 50 60 70]
Mean :  41.25
Median :  45.0
Mode : 50


In [3]:
a=np.array([2,4,6,8])
print(a[a%4==0])

[4 8]
